### PR TITLE
Update README with about me section

### PR DESCRIPTION
**Pull request by s-g-r**
Checkout the info I updated yew..

### CODE REVIEW

**Comment by eamontaaffe** [comment]
What a flog

**Comment by eamontaaffe** [comment]
# FLOG

**Comment by s-g-r** [comment]
So is this getting merged or what, I think its pretty important

**Comment by eamontaaffe** [comment]
nope, your work sucks. try harder

**Comment by eamontaaffe** [comment]
try harder

**Comment by s-g-r** [comment]
You know these are public right ...

**Comment by eamontaaffe** [comment]
lol, i can delete them

**Comment by s-g-r** [comment]
Sell out

**Pull request closed without merging**
